apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: xray-test
  namespace: default 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xray-test
  template:
    metadata:
      labels:
        app: xray-test
    spec:
      containers:
      - name: xray-test
        image: api-nodejs:xray-test-v1
        ports:
        - containerPort: 3000
--- 
apiVersion: v1 
kind: Service 
metadata:
  name: xray-test-svc
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: xray-test